name: Build Minecraft Server
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # این بخش را اضافه کنید تا جاوا ۲۵ نصب شود
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Download PaperMC
        run: wget -O paper.jar "https://fill-data.papermc.io/v1/objects/d30fae0c74092b10855f0412ca6b265c60301a013d34bc28a2a41bf5682dd80b/paper-26.1.2-69.jar"

      - name: Generate EULA and Accept
        run: |
          java -jar paper.jar --nogui || true
          sed -i 's/eula=false/eula=true/' eula.txt

      - name: Run Server (Download dependencies)
        run: |
          timeout 120s java -jar paper.jar --nogui || true

      - name: Compress Everything
        run: |
          zip -9 -r server_full.zip . -x ".git/*" -x ".github/*"

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: server-build-${{ github.run_id }}
          files: server_full.zip
